# Generated by Django 3.1.4 on 2020-12-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_a',
            new_name='a_user',
        ),
    ]
