# Generated by Django 3.1.4 on 2020-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201226_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='boolean',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
